services:

  mongoDiscordBot:
    image: mongo
    container_name: mongoDiscordBot
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo_net
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" --username root --password example --authenticationDatabase admin --quiet
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  discordbotgo:
    build: .
    image: gmlbot:latest
    container_name: discordbotgo
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mongo_net
    depends_on:
      mongoDiscordBot:
        condition: service_healthy
  mongo-express:
    image: mongo-express
    container_name: mongo-interface
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongoDiscordBot:27017/?authSource=admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      mongoDiscordBot:
        condition: service_healthy
    networks:
      - mongo_net



volumes:
  mongo-data:
networks:
  mongo_net:
    driver: bridge